export const alertConstants = {
  SUCCESS: 'ALERT_SUCCESS',
  WARNING: 'ALERT_WARNING',
  ERROR: 'ALERT_ERROR',
  INFO: 'ALERT_INFO',
  CLEAR: 'ALERT_CLEAR'
};

export const userConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  FIND_REQUEST: 'USER_FIND_REQUEST',
  FIND_SUCCESS: 'USER_FIND_SUCCESS',
  FIND_FAILURE: 'USER_FIND_FAILURE',

  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
  
  DELETE_REQUEST: 'USER_DELETE_REQUEST',
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  DELETE_FAILURE: 'USER_DELETE_FAILURE'
};